//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UrlShortener.Properties.Langs {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Lang() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UrlShortener.Properties.Langs.Lang", typeof(Lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to درباره ما.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برنامه نویسی توسط مهدی حسینی تماس : mahdidvb72@gmail.com.
        /// </summary>
        public static string AboutContent {
            get {
                return ResourceManager.GetString("AboutContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کوتاه کن.
        /// </summary>
        public static string BtnGet {
            get {
                return ResourceManager.GetString("BtnGet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بارگزاری فایل متنی.
        /// </summary>
        public static string BtnLoad {
            get {
                return ResourceManager.GetString("BtnLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شروع.
        /// </summary>
        public static string BtnStart {
            get {
                return ResourceManager.GetString("BtnStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آیا میخواهید زبان رابط کاربری را تغییر دهید؟.
        /// </summary>
        public static string ChangeLangAsk {
            get {
                return ResourceManager.GetString("ChangeLangAsk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سرویس کوتاه کننده را انتخاب کنید.
        /// </summary>
        public static string CmbService {
            get {
                return ResourceManager.GetString("CmbService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام دلخواه [اختیاری].
        /// </summary>
        public static string CustomUrl {
            get {
                return ResourceManager.GetString("CustomUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to این نام قبلا انتخاب شده است.
        /// </summary>
        public static string CustomUrlError {
            get {
                return ResourceManager.GetString("CustomUrlError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خروج.
        /// </summary>
        public static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مرحله 1: فایل متنی به این صورت ایجاد کنید (هر خط یک لینک)    http://test.com   http://test.com   مرحله دوم: فایل متنی را بارگزاری کنید   مرحله سوم: سرویس کوتاه کننده را انتخاب کنید   مرحله چهارم: ادرس ها را انتخاب کنید    مرحله پنجم: روی شروع کلیک کنید.
        /// </summary>
        public static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مخفی کردن در سیستم تری.
        /// </summary>
        public static string HideToNotify {
            get {
                return ResourceManager.GetString("HideToNotify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لینک.
        /// </summary>
        public static string Link {
            get {
                return ResourceManager.GetString("Link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نسخه جدید {0} شناسایی شد! آیا میخواهید بروزرسانی کنید؟.
        /// </summary>
        public static string NewVersion {
            get {
                return ResourceManager.GetString("NewVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برنامه در پس زمینه در حال اجرا خواهد بود و از سیستم ترای قابل دسترس خواهد بود و این پنجره به جای بستن، مخفی خواهد شد. آیا موافقید؟.
        /// </summary>
        public static string OnClosingMessage {
            get {
                return ResourceManager.GetString("OnClosingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to باز کردن پنل.
        /// </summary>
        public static string OpenPanel {
            get {
                return ResourceManager.GetString("OpenPanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطایی رخ داد لطفا دوباره امتحان کنید.
        /// </summary>
        public static string OpizoError {
            get {
                return ResourceManager.GetString("OpizoError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کپی شد!.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خانه.
        /// </summary>
        public static string Tab_Home {
            get {
                return ResourceManager.GetString("Tab_Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لیست.
        /// </summary>
        public static string Tab_List {
            get {
                return ResourceManager.GetString("Tab_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to روی صفحه.
        /// </summary>
        public static string TopMost {
            get {
                return ResourceManager.GetString("TopMost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لینک موردنظر را اینجا بنویسید....
        /// </summary>
        public static string TxtUrl {
            get {
                return ResourceManager.GetString("TxtUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بروزرسانی.
        /// </summary>
        public static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شما از آخرین نسخه استفاده میکنید {0}.
        /// </summary>
        public static string UpdateMessage {
            get {
                return ResourceManager.GetString("UpdateMessage", resourceCulture);
            }
        }
    }
}
